learning_log/learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

# 包含项目中的应用程序的URL模式（所有URL忽略基础URL http://localhost:8000/）
urlpatterns = [
    # django.conf.urls(
    #     regex=用于匹配URL的正则表达式字符串<字符串>: 脱字符^表示匹配字符串的开头; 美元符号$表示匹配字符串的结尾;
    #         /(?P<变量名>\d+)/表示匹配/和/间的一组字符串格式数字，并将字符串转换为数字然后赋值给变量，再传入视图函数处理;
    #         ()表示捕获URL中的值作为视图函数的参数; ?P<变量名>表示将匹配的字符串切取、处理并赋值给变量; \d表示数字; +表示可以不止一位
    #         | 无默认值,
    #     view=视图函数<函数> | 无默认值,
    #     kwargs=视图函数除URL提供的参数和用户请求外的参数名及其实参<字典>: 其中的键值对会按照随机顺序传入视图函数中;
    #         键为参数名的字符串，值为实参; 常用键值对："templeta_name":模板路径<字符串> |,
    #     name=别名<字符串>: 对本条URL取别名 |)
    # 返回新创建的URL和视图函数之间的映射关系，当用户访问某个URL时，Django将请求和其他参数发送给对应的视图函数来处理
    # django.contrib.admin.site.urls()
    # 返回管理网站可以请求的所有视图函数
    # 以admin/开头的URL，即管理网站的URL
    url(r"^admin/", admin.site.urls),
    # django.conf.urls.include(
    #     arg=URLconf模块（urls.py）名称<字符串>: 如"应用程序文件夹.urls" | 无默认值,
    #     namespace=包含的URL条目的命名空间<字符串>: 用于与同项目中的其他URL区分开 |,
    #     其他参数: 均有默认值)
    # 剔除掉前面匹配到的部分后，将剩下的部分交给本函数中的另一个URLconf模块（urls.py）处理
    # users的URL
    url(r"^users/", include("users.urls", namespace="users")),
    # 空字符URL，即learning_logs的URL
    url(r"", include("learning_logs.urls", namespace="learning_logs")),
]

learning_log/learning_logs/urls.py
"""定义learning_logs的URL模式"""

from django.conf.urls import url

# .表示文件所在文件夹
from . import views

urlpatterns = [
    # 主页
    # 开头结尾间没有东西的URL，与基础URL匹配
    url(r"^$", views.index, name="index"),
    # 显示全部主题的网页
    url(r"^topics/$", views.topics, name="topics"),
    # 显示特定主题全部条目的网页
    url(r"^topics/(?P<topic_id>\d+)/$", views.topic, name="topic"),
    # 用户添加新主题的网页
    url(r"^new_topic/$", views.new_topic, name="new_topic"),
    # 用户添加新条目的网页
    url(r"^new_entry/(?P<topic_id>\d+)/$", views.new_entry, name="new_entry"),
    # 用户编辑主题的网页
    url(r"^edit_topic/(?P<topic_id>\d+)/$", views.edit_topic, name="edit_topic"),
    # 用户编辑条目的网页
    url(r"^edit_entry/(?P<entry_id>\d+)/$", views.edit_entry, name="edit_entry"),
    # 用户删除主题的网页
    url(r"^delete_topic/(?P<topic_id>\d+)/$", views.delete_topic, name="delete_topic"),
    # 用户确认删除主题的网页
    url(
        r"^delete_topic_yes/(?P<topic_id>\d+)/$",
        views.delete_topic_yes,
        name="delete_topic_yes",
    ),
    # 用户删除条目的网页
    url(r"^delete_entry/(?P<entry_id>\d+)/$", views.delete_entry, name="delete_entry"),
    # 用户确认删除条目的网页
    url(
        r"^delete_entry_yes/(?P<entry_id>\d+)/$",
        views.delete_entry_yes,
        name="delete_entry_yes",
    ),
]

learning_log/users/urls.py
"""为应用程序users定义URL模式"""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # 登录页面
    # django.contrib.auth.views.login(
    #     request=用户请求<django.http.request.HttpRequest类> | 无默认值,
    #     template_name=模板路径<字符串> | "registration/login.html",
    #     其他参数: 均有默认值)
    # Django默认登录账户视图函数
    url(r"^login/$", login, {"template_name": "users/login.html"}, name="login"),
    # 注销账户
    url(r"^logout/$", views.logout_view, name="logout"),
    # 注册账户
    url(r"^register/$", views.register, name="register"),
]

learning_log/learning_logs/models.py
from django.contrib.auth.models import User
from django.db import models

# 在这里创建模型


class Topic(models.Model):
    """用户学习的主题"""

    # django.db.models.CharField(
    #     verbose_name=<字符串> | None,
    #     name=<字符串> | None,
    #     primary_key=<布尔> |,
    #     max_length=在数据库中预留多少空间<整型数>: 单位为字符 | None,
    #     其他参数: 均有默认值)
    # 返回依参数新创建的由字符或文本组成的数据CharField实例
    # 用于模拟存储少量文本的数据，如名称、标题或城市
    text = models.CharField(max_length=200)
    # django.db.models.DateTimeField(
    #     verbose_name=<字符串> | None,
    #     name=<字符串> | None,
    #     auto_now=<布尔> |,
    #     auto_now_add=是否在创建实例时自动设置为当前日期和时间<布尔> | True,
    #     其他参数: 均有默认值)
    # 返回依参数新创建的记录日期和时间的数据DateTimeField实例
    date_added = models.DateTimeField(auto_now_add=True)
    # ForeignKey()函数详解加下
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    # django.db.models.Model.__str__()
    # 指定在网页上有关模型默认显示为哪些数据即模型实例的字符串表示
    # Python 2.7中用__unicode__()代替
    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """学到的有关每个主题的具体知识"""

    # django.db.models.ForeignKey(
    #     to=关联的目标模型<字符串/类>: 字符串实参指明模型的路径 | 无默认值,
    #     on_delete=当关联实例被删除时的处理办法<函数>: django.db.models模块定义了多个函数，
    #         CASCADE级联删除，删除关联对象时同时删除本对象、
    #         PROTECT保护，删除关联对象时引发错误ProtectedError，防止删除关联对象、
    #         SET_NULL删除关联对象时属性设置为空（前提是blank=True、null=True即创建该属性时允许为空）、
    #         SET_DEFAULT删除关联对象时设置为默认值（前提是传递了默认值default实参）、
    #         SET(值/表达式)删除关联对象时设定为自定义值、
    #         DO_NOTHING除删除关联对象外什么也不做 | 无默认值)
    # 返回依参数新创建的本模型与目标模型间的外键（关联关系）ForeignKey实例
    # 外键是数据库术语，用于引用数据库中的另一条记录
    # 每个主题Topic实例创建时，给它分配一个键或ID
    # 将每个条目Entry实例关联到主题Topic实例时，使用主题Topic实例的键
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    # django.db.models.TextField()
    # 返回依参数新创建的由不限制长度的大量文本组成的数据TextField实例
    text = models.TextField()
    # 记录日期和时间的数据DateTimeField实例用于确定显示条目的顺序和显示时间戳
    date_added = models.DateTimeField(auto_now_add=True)

    # 嵌套类的定义发生在外部类的定义内，可以像普通类一样定义属性和方法，并且可以被实例化和使用
    # 外部类.嵌套类(嵌套类__init__()实参列表)
    # 返回新创建的嵌套类实例
    # 通过传递外部类的实例作为嵌套属性的初始化参数或通过其他方式将外部类的属性传递给嵌套类，可以在嵌套类中访问外部类的属性
    # 嵌套类Mate用于管理模型的额外信息
    class Mate:
        # 设置特殊属性，用于在需要时Django使用Entries表示多个条目
        # 如果不定义这个类，Django使用Entrys来表示多个条目
        verbose_name_plural = "entries"

    def __str__(self):
        """返回模型的字符串表示"""
        # 网页上显示文本的前50个字符
        return self.text[:50] + "..."

learning_log/learning_logs/forms.py
# 导入表单模块
from django import forms

# 导入模型
from .models import Entry, Topic


class TopicForm(forms.ModelForm):
    # 内嵌类，用于指定根据哪个模型创建表单
    class Meta:
        model = Topic
        # 该表单包含字段text
        # 输入给该字段对应表单元素的数据会赋值给所属模型实例的、名字与该字段相同的属性
        fields = ["text"]
        # 不为字段生成标签
        labels = {"text": ""}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["text"]
        labels = {"text": ""}
        # django.forms.Textarea(
        #     attrs=小部件样式<字典>: 常用键值对："cols":宽度<整型数>: 默认40列)
        # 返回新创建的输入小部件
        # 创建输入小部件
        widgets = {"text": forms.Textarea(attrs={"cols": 80})}

learning_log/learning_logs/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render

# 在这里创建视图
# 导入表单
from .forms import EntryForm, TopicForm

# 导入模型
from .models import Entry, Topic


def index(request):
    """学习笔记的主页"""
    # django.shortcuts.render(
    #     request=原始请求<> | 无默认值,
    #     template_name=要渲染的模板名称<字符串/列表>: 模板名称为自定义html文件或其路径，
    #         可以选择绝对路径或相对路径，相对路径起点为应用程序目录\templates\;
    #         接收列表实参时，列表的元素为模板名称，Django将按照给定列表的顺序查找模板文件 | 无默认值,
    #     context=要传递给模板的数据<字典>: 字典键值对为 模板中的变量名<字符串>:传递给模板变量的数据<> | None: 不传递数据,
    #     其他参数: 均有默认值)
    # 根据请求，将数据渲染的到指定的模板中，生成并返回接收请求后的响应（网页）
    return render(request, "learning_logs/index.html")


@login_required
def topics(request):
    """显示所有主题"""
    # django.db.models.Model子类.objects.order_by(
    #     *field_names: 接收子类属性字段，以字符串表示; 依据该字段进行排序)
    # 返回模型的所有实例依模型的某个属性排序后的集合
    # topics = Topic.objects.order_by("date_added")
    # django.db.models.Model子类.objects.filter(
    #     *args,
    #     **kwargs: 接收数个关键字实参，作为筛选条件，条件的格式为模型属性=目标值)
    # 返回模型的所有实例中的符合条件的实例组成的集合，类型为django.db.models.manager.Manager.BaseManager（模型管理器）类
    topics = Topic.objects.filter(owner=request.user).order_by("date_added")
    context = {"topics": topics}
    return render(request, "learning_logs/topics.html", context)


@login_required
def topic(request, topic_id):
    """显示特定主题全部条目"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        # raise Http404
        # 抛出404异常
        raise Http404
    # django.db.models.Model实例1.[django.db.models.Model子类2小写名称]_set.order_by(
    #     用于排序的属性字段<字符串>: 以属性名字符串表示; 字符串以-开头表示按降序排列)
    # 返回关联本模型实例1的所有模型2实例依模型2实例的某个属性排序后的集合
    # 获取所有条目依时间并由近到远排序
    entries = topic.entry_set.order_by("-date_added")
    context = {"topic": topic, "entries": entries}
    return render(request, "learning_logs/topic.html", context)


@login_required
def new_topic(request):
    """添加新主题"""
    # django.http.resquest.HttpRequest（请求）实例常用属性：
    # method<字符串>：标识请求所使用的HTTP方法，如GET获取、POST提交、PUT等
    # GET<django.http.QueryDict类（类似字典）>：包含GET请求中的所有参数及其实参，键和值都是字符串类型
    # POST<django.http.QueryDict类（类似字典）>：包含POST请求中提交的除文件外的表单数据参数及其实参，键和值都是字符串类型
    #     常用键值对："password1":注册网页中输入密码的框提交的数据、"password2":注册网页中确认输入密码的框提交的数据
    # FILES<django.http.QueryDict类（类似字典）>：包含所有的上传文件数据，
    #     每个键是html文件中上传文件的标签input的name属性，每个值是一个上传的文件数据
    # COOKIES<字典>：包含了一次请求的Cookie信息，键和值都是字符串
    # META<字典>：包含了所有的HTTP头部信息; 常用键值对：
    #     CONTENT_LENGTH:标识请求消息正文的长度: 对于POST请求这个请求头是必需的、
    #     CONTENT_TYPE:请求正文的MIME类型: 对应于post和hello请求，它的值可以是text和plain、
    #     HTTP_HOST:客户端发送的HTTP主机头、
    #     HTTP_USER_AGENT:浏览器的类型，通常被称为UA: 适用于视图准备的网页随浏览器的不同而不同的情况、
    #     REMOTE_ADDR:客户端的IP地址: 可以用于记录日志或根据IP确定地域再做处理、
    #     REMOTE_HOST:客户端的主机名、
    #     REQUEST_METHOD:请求方法: GET、POST等、
    #     SERVER_NAME:服务器的主机名、
    #     SERVER_PORT:服务器的端口号<字符串>: 如"8000"
    # user<django.contrib.auth.models.User（用户）类/django.contrib.auth.models.AnonymousUser（匿名用户）类>:标识当前登录用户: 在用
    #     户未登录时，被设置为匿名用户

    # django.contrib.auth.models.User（用户）实例常用属性：
    # username<django.db.models.CharField类>：用户名
    if request.method != "POST":
        # 未提交主题时，创建新表单
        # django.forms.ModelForm子类(
        #     data=填入表单的数据<字符串> | None: 表单各元素空白,
        #     files,
        #     auto_id,
        #     prefix,
        #     initial,
        #     error_class,
        #     label_suffix,
        #     empty_permitted,
        #     instance=创建表单时表单填入哪个模型实例的属性<django.db.models.Model子类> | None: 不填入数据,
        #     其他参数，均有默认值)
        # 返回新创建的表单实例
        form = TopicForm()
    else:
        # 提交主题后，对数据进行处理，并返回显示所有主题的网页
        form = TopicForm(request.POST)
        # django.forms.ModelForm子类实例.is_valid()
        # 检查用户是否填写表单的所有必填字段（默认所有字段必填），以及输入的数据符合要求
        if form.is_valid():
            # django.forms.ModelForm子类实例.save(
            #     commit=是否立即将数据存入数据库<布尔>: True立即存储到数据库内;
            #         False暂不存储到数据库内，之后手动随返回的模型实例一起保存，适用于模型实例需要修改后才存储的场景
            #         | True)
            # 返回新创建的存储填入表单的数据的表单所属模型的实例，并确定是否立即保存该实例到数据库
            # form.save()
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            # django.core.urlresolvers.reverse(
            #     viewname=URL别名<字符串>: "命名空间:URL别名" | None,
            #     urlconf,
            #     args=URL需要的参数列表<列表>: 在URL别名对应的URL尾加上 参数/; 列表元素为URL的参数 | None: 无参数,
            #     其他参数: 均有默认值)
            # 已知URL别名及URL参数，通过逆向解析获取URL，返回该URL的字符串
            # django.http.HttpResponseRedirect(
            #     redirect_to=URL<字符串>,
            #     其他参数: 均有默认值)
            # 将浏览器重新定向到URL对应的网页
            return HttpResponseRedirect(reverse("learning_logs:topics"))

    context = {"form": form}
    return render(request, "learning_logs/new_topic.html", context)


@login_required
def new_entry(request, topic_id):
    """在特定主题添加新条目"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    if request.method != "POST":
        # 未提交条目时，创建新表单
        form = EntryForm()
    else:
        # 提交条目后，对数据进行处理，并返回显示所有条目的网页
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            # 使条目关联到主题
            new_entry.topic = topic
            # django.db.models.Model子类实例.save()
            # 将模型实例存储到数据库内
            new_entry.save()
            return HttpResponseRedirect(reverse("learning_logs:topic", args=[topic_id]))

    context = {"topic": topic, "form": form}
    return render(request, "learning_logs/new_entry.html", context)


@login_required
def edit_topic(request, topic_id):
    """编辑主题"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    if request.method != "POST":
        # 未编辑主题时，创建表单，填入原条目
        form = TopicForm(instance=topic)
    else:
        # 编辑并提交主题后，对数据进行处理，并返回显示所有条目的网页
        # 根据既有主题创建表单，再根据请求修改条目
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("learning_logs:topics"))

    context = {"topic": topic, "form": form}
    return render(request, "learning_logs/edit_topic.html", context)


@login_required
def edit_entry(request, entry_id):
    """编辑条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != "POST":
        # 未编辑条目时，创建表单，填入原条目
        form = EntryForm(instance=entry)
    else:
        # 编辑并提交条目后，对数据进行处理，并返回显示所有条目的网页
        # 根据既有条目创建表单，在根据请求修改条目
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("learning_logs:topic", args=[topic.id]))

    context = {"entry": entry, "topic": topic, "form": form}
    return render(request, "learning_logs/edit_entry.html", context)


@login_required
def delete_topic(request, topic_id):
    """删除主题的网页"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    context = {"topic": topic}
    return render(request, "learning_logs/delete_topic.html", context)


@login_required
def delete_topic_yes(request, topic_id):
    """确认删除主题"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    # django.db.models.Model子类实例.delete()
    # 删除模型实例
    topic.delete()
    return HttpResponseRedirect(reverse("learning_logs:topics"))


@login_required
def delete_entry(request, entry_id):
    """删除条目的网页"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    context = {"entry": entry, "topic": topic}
    return render(request, "learning_logs/delete_entry.html", context)


@login_required
def delete_entry_yes(request, entry_id):
    """确认删除条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    entry.delete()
    return HttpResponseRedirect(reverse("learning_logs:topic", args=[topic.id]))

learning_log/learning_logs/templates/learning_logs/base-outdated.html
<p>
    <!--项目名和“主题”独立成段，并带有到主页和显示所有主题的页面的超链接-->
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> - 
    <a href="{% url 'learning_logs:topics' %}">Topics</a> - 
    <!--
        django.contrib.auth.models.User（用户）实例.is_authenticated()
        django.contrib.auth.models.AnonymousUser（匿名用户）实例.is_authenticated()
        返回表示用户是否登录的类似布尔的值
    -->
    {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">register</a> - 
        <a href="{% url 'users:login' %}">log in</a>
    {% endif %}
</p>

<!--块标签，用于占位，实际信息由子模板指定-->
{% block content %}{% endblock content %}

learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <!--{% load static %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <script src="{% static 'js/bootstrap.min.js' %}"></script>-->
        
        <!--<link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>-->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>学习笔记</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>

    <body>

        <!--Static navbar-->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    </button>
                    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                        学习笔记
                    </a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'learning_logs:topics' %}">主题</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a>你好，{{ user.username }}.</a></li>
                            <li><a href="{% url 'users:logout' %}">注销</a></li>
                        {% else %}
                            <li><a href="{% url 'users:register' %}">注册</a></li>
                            <li><a href="{% url 'users:login' %}">登录</a></li>
                        {% endif %}
                    </ul>
                </div><!--/.nav-collapse -->

            </div>
        </nav>

        <div class="container">
            
            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>

        </div><!-- /container -->
    </body>
</html>

learning_log/learning_logs/templates/learning_logs/delete_entry-outdated.html
<!--父模板-->
{% extends "learning_logs/base.html" %}

<!--父模板占位块的实现-->
{% block content %}

    <!--显示主题，并超链接到显示主题所有条目的网页-->
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <p>Delete the entry?</p>

    <!--显示条目-->
    <ul>
        <li>
            <p>{{ entry.date_added|date:"M d, Y H:i" }}</p>
            <p>{{ entry.text|linebreaks }}</p>
            <p>
                <!--确认删除-->
                <a href="{% url 'learning_logs:delete_entry_yes' entry.id%}">Yes</a>- - - - - - - - - - - - - - - - - - - - - - - - -
                <!--不删除-->
                <a href="{% url 'learning_logs:topic' topic.id %}">No</a>
            </p>
        </li>
    </ul>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/delete_entry.html
<!--父模板-->
{% extends "learning_logs/base.html" %}

<!--父模板占位块的实现-->
{% block header %}
    <!--显示主题，并超链接到显示主题所有条目的网页-->
    <h2>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h2>
    <h3>您确定要删除该条目吗？</h3>
{% endblock header %}

{% block content %}

    <!--显示条目-->
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4>
                {{ entry.date_added|date:"Y年 M d日, H:i" }}
            </h4>
        </div>
        <div class="panel-body">
            <h3>
                {{ entry.text|linebreaks }}
            </h3>
        </div>
    </div>

    <h3>
        <!--确认删除-->
        <a href="{% url 'learning_logs:delete_entry_yes' entry.id%}">确定</a>- - - - - - - - - - - - - - - - - - - - - - - - -
        <!--不删除-->
        <a href="{% url 'learning_logs:topic' topic.id %}">取消</a>
    </h3>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic-outdated.html
<!--父模板-->
{% extends "learning_logs/base.html" %}

<!--父模板占位块的实现-->
{% block content %}

    <p>Topics: {{ topic }}</p>

    <p>Entries:</p>

    <!--超链接到添加条目网页-->
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add a new entry</a>
    </p>

    <!--条目罗列-->
    <ul>
        {% for entry in entries %}
            <li>
                <p>{{ entry.date_added|date:"M d, Y H:i" }}</p>
                <p>{{ entry.text|linebreaks }}</p>
                <p>
                    <!--修改条目-->
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit the entry</a>- - - - - - - - - - - - - - - - - - - - - - - - -
                    <!--删除条目-->
                    <a href="{% url 'learning_logs:delete_entry' entry.id %}">Delete the entry</a>
                </p>
            </li>
        {% empty %}
            <li>
                There are no entries for this topic yet.
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
<!--父模板-->
{% extends "learning_logs/base.html" %}

<!--父模板占位块的实现-->
{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}

    <!--超链接到添加条目网页-->
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">添加一个新条目</a>
    </p>

    <!--条目罗列-->
    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added|date:"Y年 M d日, H:i" }}
                    <small>
                        <!--修改条目-->
                        <a href="{% url 'learning_logs:edit_entry' entry.id %}">编辑条目</a>- - - - - - - - - - - - - - - - - - - - - - - - -
                        <!--删除条目-->
                        <a href="{% url 'learning_logs:delete_entry' entry.id %}">删除条目</a>
                    </small>
                </h3>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        这个主题还没有条目。
    {% endfor %}

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
<!--父模板-->
{% extends "learning_logs/base.html" %}

<!--父模板占位块的实现-->
{% block header %}
    <h1>主题</h1>
{% endblock header %}

{% block content %}

    <!--主题罗列-->
    <ul>
        {% for topic in topics %}
            <li>
                <h4>{{ topic.date_added|date:"Y年 M d日，H:i" }}</h4>
                <h3>
                    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                </h3>
                <h4>
                    <!--修改主题-->
                    <a href="{% url 'learning_logs:edit_topic' topic.id %}">编辑主题</a>- - - - - - - - - - - - - - - - - - - - - - - - -
                    <!--删除主题-->
                    <a href="{% url 'learning_logs:delete_topic' topic.id %}">删除主题</a>
                </h4>
            </li>
        {% empty %}
            <li>还没有添加主题。</li>
        {% endfor %}
    </ul>
    <!--添加主题的超链接-->
    <h3><a href="{% url 'learning_logs:new_topic' %}">添加一个新主题</a></h3>
{% endblock content %}